app = "ai-navigator-backend-vlurvebi"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  PYTHONPATH = "/app"
  ENVIRONMENT = "production"
  BACKEND_CORS_ORIGINS = '["https://product-ai-app-y6r2cpbq.devinapps.com"]'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
