name: Frontend CI

on:
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./frontend
        run: |
          npm install

      - name: Run tests
        working-directory: ./frontend
        run: |
          npm run test

      - name: Build
        working-directory: ./frontend
        run: |
          npm run build

      - name: Lint
        working-directory: ./frontend
        run: |
          npm run lint
